apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: climbear-external-secret
spec:
  refreshInterval: 1h # 시크릿 갱신 주기
  secretStoreRef:
    name: aws-secrets-mgr
    kind: SecretStore
  target:
    name: climbear-k8s-secret # 생성될 로컬 K8s Secret 이름
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "prod/climbear"