# application.yml - Gateway 공통 설정
spring:
  application:
    name: climbear-gateway
  profiles:
    active: local
    group:
      local: "common,local"
      dev: "common,dev"
      prod: "common,prod"